//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int ID { get; set; }
        public decimal Origin_Price { get; set; }
        public Nullable<decimal> Promotion_Price { get; set; }
        public decimal Final_Price { get; set; }
        public int Product_ID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
